package com.zzkMavenJfinal.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

import com.zzkMavenJfinal.model.SysUser;

/**
 * Generated by JFinal, do not modify this file.
 * 
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tb_vote", "Id", SysUser.class);
		arp.addMapping("tb_Enclosure", "Id", tb_Enclosure.class);
		arp.addMapping("tb_staff", "Id", tb_staff.class);
	}
}
